# Generated by Django 4.2.5 on 2023-10-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
