# Generated by Django 4.2.5 on 2023-10-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_delete_admin_alter_bet_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='oddDraw',
            field=models.FloatField(default=2, max_length=20),
        ),
    ]
