# Generated by Django 4.2.5 on 2023-10-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_game_odddraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
