# Generated by Django 4.2.5 on 2023-10-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_profile_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_betted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betted', models.CharField(default='', max_length=70)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='app.game')),
            ],
        ),
        migrations.AlterField(
            model_name='bet',
            name='games',
            field=models.ManyToManyField(related_name='bets', to='app.game_betted'),
        ),
    ]
