# Generated by Django 4.2.5 on 2023-10-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_bet_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='win',
            field=models.CharField(default='waiting', max_length=70),
        ),
    ]
