# Generated by Django 4.2.5 on 2023-11-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_game_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
