# Generated by Django 4.2.5 on 2023-11-11 13:08

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='none', null=True, upload_to='post_images/'),
        ),
    ]
