# Generated by Django 4.2.5 on 2023-11-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_team_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
    ]
