# Generated by Django 4.2.5 on 2023-12-17 17:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=10)),
                ('Last_Name', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_equipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameStore.equipa')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='<PASSWORD>', max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.DateField()),
                ('fase', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=10)),
                ('equipas', models.ManyToManyField(to='GameStore.equipa')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameStore.modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golos_eq_casa', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)])),
                ('golos_eq_fora', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)])),
                ('tempo_fim_1p', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tempo_fim_2p', models.DecimalField(decimal_places=1, max_digits=3)),
                ('data', models.DateField()),
                ('equipa_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameStore.equipa')),
                ('equipa_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameStore.jogador')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameStore.liga')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameStore.liga')),
            ],
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameStore.liga')),
                ('players', models.ManyToManyField(to='GameStore.jogador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameStore.user')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('tempo', models.CharField(max_length=5)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameStore.jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameStore.jogo')),
            ],
        ),
        migrations.AddField(
            model_name='equipa',
            name='grupos',
            field=models.ManyToManyField(to='GameStore.grupo'),
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrPontos', models.DecimalField(decimal_places=1, max_digits=10)),
                ('equipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameStore.equipa')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameStore.liga')),
            ],
        ),
    ]
