# Generated by Django 4.2.5 on 2023-12-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='nome',
            field=models.CharField(default='', max_length=10),
        ),
    ]
