# Generated by Django 4.2.5 on 2023-12-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0002_liga_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='nome',
            field=models.CharField(default='', max_length=20),
        ),
    ]
