# Generated by Django 4.2.5 on 2023-12-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0004_user_firstname_user_lastname_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='Last_Name',
        ),
        migrations.AddField(
            model_name='jogador',
            name='fullname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
