# Generated by Django 4.2.5 on 2023-12-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0005_remove_jogador_first_name_remove_jogador_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='pontos',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
