# Generated by Django 4.2.5 on 2023-12-17 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0009_alter_jogo_tempo_fim_1p_alter_jogo_tempo_fim_2p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='golos_eq_casa',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='golos_eq_fora',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)]),
        ),
    ]
