# Generated by Django 4.2.5 on 2023-12-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0010_alter_jogo_golos_eq_casa_alter_jogo_golos_eq_fora'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='nr_ocorrencias',
            field=models.IntegerField(default=0),
        ),
    ]
