# Generated by Django 4.2.5 on 2023-12-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0011_evento_nr_ocorrencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tempo',
            field=models.CharField(max_length=6),
        ),
    ]
