# Generated by Django 4.2.5 on 2023-12-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0012_alter_evento_tempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='nr_ocorrencias',
        ),
    ]
