# Generated by Django 4.2.5 on 2023-12-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GameStore", "0013_remove_evento_nr_ocorrencias"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
