# Generated by Django 4.2.5 on 2023-12-20 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0014_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasyteam',
            name='liga',
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='modalidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GameStore.modalidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='<PASSWORD>', max_length=20),
        ),
    ]
