# Generated by Django 4.2.5 on 2023-12-23 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("GameStore", "0014_user_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fantasyteam",
            name="liga",
        ),
        migrations.AddField(
            model_name="fantasyteam",
            name="modalidade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="GameStore.modalidade",
            ),
        ),
        migrations.AddField(
            model_name="modalidade",
            name="nr_jogadores",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fantasyteam",
            name="capitan",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="fantasyteam",
            name="players",
            field=models.ManyToManyField(default=[], to="GameStore.jogador"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="<PASSWORD>", max_length=20),
        ),
    ]
