# Generated by Django 3.2.10 on 2023-12-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0015_remove_fantasyteam_liga_fantasyteam_modalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='nr_jogadores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='capitan',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='players',
            field=models.ManyToManyField(default=[], to='GameStore.Jogador'),
        ),
    ]
